### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by nevermoresss** [AndreiD/TSnackBar#41]
```
Caused by: java.lang.NullPointerException:
Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
at com.androidadvance.topsnackbar.TSnackbar.<init>(TSnackbar.java:129)
at com.androidadvance.topsnackbar.TSnackbar.make(TSnackbar.java:138)
```

**Comment by manenga** [comment]
I had the same issue @nevermoresss you have to make sure the view you're using in TSnackbar.make(view.findViewById(R.id.confirm_container) is either a CoordinatorLayout or FrameLayout or at least an instance of either of them.

**Comment by nevermoresss** [comment]
thx ~ brother @TheBachelor
